/** @format */

"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../components/lib/utils";
import SideNavbar from "@/components/SideNavbar";
import { usePathname } from "next/navigation"; 

// inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "YYV Employee Dashboard",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const hideSidebar = pathname === "/login"; // Hide sidebar if on login page
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
         // inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        {/* <p className="border">Sidebar</p> */}
        {/* Conditionally render the sidebar */}
        {!hideSidebar && <SideNavbar />}
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
